{
 "title": "Performance over time",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": "SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema';"
   },
   { "name": "endpoint", "query": "SELECT path FROM $application;" }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.throughput\nFROM (\n    SELECT id, path, throughput\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.successful\nFROM (\n    SELECT id, path, successful\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.failed\nFROM (\n    SELECT id, path, failed\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Min response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.min\nFROM (\n    SELECT id, path, min\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.mean\nFROM (\n    SELECT id, path, mean\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Max response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.max\nFROM (\n    SELECT id, path, max\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "25th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q25\nFROM (\n    SELECT id, path, q25\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Median response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.median\nFROM (\n    SELECT id, path, median\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "Standard deviation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.std_dev\nFROM (\n    SELECT id, path, std_dev\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "75th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q75\nFROM (\n    SELECT id, path, q75\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "90th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q90\nFROM (\n    SELECT id, path, q90\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "95th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q95\nFROM (\n    SELECT id, path, q95\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "99th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q99\nFROM (\n    SELECT id, path, q99\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  },
  {
   "title": "99.9th percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  outerq.timestamp AS \"time\",\n  outerq.commit AS metric,\n  subq.q999\nFROM (\n    SELECT id, path, q999\n    FROM example\n    WHERE path = '$endpoint'\n    GROUP BY id, path\n) subq JOIN example outerq on outerq.id = subq.id\nORDER BY outerq.timestamp ASC;"
    }
   ]
  }
 ]
}